backend:
  name: git-gateway
  branch: main # Tên branch trên github để lưu trữ dữ liệu

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: your-public-key

collections: # Các collection để quản lý dữ liệu, ở đây tạo 2 collection là blog và pages
  - name: "blog" # Tên collection, chức năng quản lý blog, tạo mới, sửa, xóa
    label: "Blog" # Label hiển thị
    folder: "blog" # Thư mục chứa các file blog
    create: true
    slug: "{{slug}}" # Tạo slug từ title để tạo URL
    extension: "html"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    template: "blog-template.html" # Sử dụng template HTML
    # Cách truy cập vào blog: localhost/blog/slug

  - name: "pages" # Tên collection, chức năng quản lý các trang, tạo mới, sửa, xóa nội dung, trang
    label: "Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "index.html" # nguồn trang để edit
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
